test_app/config/routes.rb
TestApp::Application.routes.draw do
  post 'projects/sort', :to => 'projects#sort', :as => :projects_sort

  resources :projects do
    resources :entries
    match 'entries/sort', :to => 'entries#sort', :as => :entries_sort
  end


  root :to => 'pages#home'
end

test_app/app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :project
  acts_as_list :scope => :project
  default_scope order('position ASC')

  def as_json(options = {})
    {
      :id => self.id,
      :title => escape(self.title),
      :thought => escape(self.thought),
      :project_id => self.project_id,
    }
  end

  private

  def escape(s)
    ERB::Util.html_escape(s)
  end
end

test_app/app/models/project.rb
class Project < ActiveRecord::Base
  has_many :entries, 
    :dependent => :destroy,
    :order => "position ASC"

  acts_as_list

  default_scope order('position ASC')

  validates :permalink, :name, :presence => true
  validates :permalink, :uniqueness => true

  before_validation :set_permalink, :on => :create

  def to_param
    permalink
  end

  def self.find_by_param!(param)
    self.find_by_permalink!(param)
  end

  def as_json(opts = {})
    {
      :id => id,
      :name => escape(name),
      :created_at => created_at,
      :updated_at => updated_at,
      :permalink => permalink,
      :param => to_param,
    }
  end

  private

  def set_permalink
    self.permalink = (name || '').parameterize if permalink.blank?
  end

  def escape(s)
    ERB::Util.html_escape(s)
  end
end

test_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

test_app/app/controllers/entries_controller.rb
class EntriesController < ApplicationController

  def index
    @project = Project.find_by_param!(params[:project_id])
    @entries = @project.entries

    respond_to do |format|
      format.json { render :json => @entries }
    end
  end

  def new
    @project = Project.find_by_param!(params[:project_id])
    @entry = @project.entries.build

    respond_to do |format|
      format.json { render :json => {
        :html => render_to_string(:partial => 'entries/form.html.haml' )
      } }
    end
  end

  def create
    @project = Project.find_by_param!(params[:project_id])
    @entry = @project.entries.build(params[:entry])

    respond_to do |format|
      if @entry.save
        format.json { render :json => @entry }
      else
        # error handling ...
      end
    end
  end

  def edit
    @project = Project.find_by_param!(params[:project_id])
    @entry = @project.entries.find(params[:id])
    respond_to do |format|
      format.json { render :json => {
        :html => render_to_string(:partial => 'entries/form.html.haml' )
      } }
    end
  end

  def update
    @project = Project.find_by_param!(params[:project_id])
    @entry = @project.entries.find(params[:id])
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.json { render :json => @entry }
      else
        # error handling ...
      end
    end
  end

  def destroy
    @project = Project.find_by_param!(params[:project_id])
    @entry = @project.entries.find(params[:id])
    @entry.destroy
    respond_to do |format|
      format.json { render :json => @entry }
    end
  end

  def sort
    project = Project.find_by_param!(params[:project_id])
    entries = project.entries
    entries.each do |e|
      e.position = params['entry'].index(e.id.to_s) + 1
      e.save
    end
    render :nothing => true
  end
end

test_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @projects = Project.all
  end

end

test_app/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.json { render :json => @projects }
    end
  end

  def new
    @project = Project.new
    respond_to do |format|
      format.json { render :json => {
        :object => @project,
        :html   => render_to_string(:partial => 'projects/form.html.haml', :locals => { :project => @project }),
        :action => 'new',
        :kind   => 'project'
      } }
    end
  end

  def create
    @project = Project.create(params[:project])
    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path }
      else
        format.html { render 'new' }
      end
    end
  end

  def update
    @project = Project.find_by_param!(params[:id])
    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to edit_project_url(@project) }
      else
        format.html { render 'edit' }
      end
    end
  end

  def edit
    @project = Project.find_by_param!(params[:id])
  end

  def show
    @project = Project.find_by_param!(params[:id])
  end

  def destroy
    @project = Project.find_by_param!(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { render :json => @project }
    end
  end

  def sort
    project = Project.all
    project.each do |p|
      p.position = params['project'].index(p.id.to_s) + 1
      p.save
    end
    render :nothing => true
  end
end

test_app/app/helpers/application_helper.rb
module ApplicationHelper
  def is_active?(page)
    if page.to_s.match controller.action_name
      "active"
    else
      nil
    end
  end

  def body_class
    controller.controller_name
  end

  def content_class
    controller.action_name
  end
end

test_app/app/helpers/entries_helper.rb
module EntriesHelper
end

test_app/app/helpers/pages_helper.rb
module PagesHelper
end

test_app/app/helpers/projects_helper.rb
module ProjectsHelper
end

test_app/app/views/entries/_entry.html.haml
%li
  %h2=entry.title

test_app/app/views/entries/_form.html.haml
=form_for [ @project, @entry ] do |f|
  %p
    =f.label :title
    =f.text_field :title

  %p
    =f.submit

test_app/app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{'charset'=>'utf-8'}
    %title new app
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"

    = render 'shared/backbone/templates'
    = render 'shared/extra_head'

    = csrf_meta_tags

  %body{ :class => body_class }

    =render 'shared/header'
    =render 'shared/navigation'
    =render 'shared/notice'

    %section#content{ :class => content_class }

      =yield

    =render 'shared/footer'

test_app/app/views/pages/home.html.haml
%h1
  Hello. Feel free to test this out.

%p
  Click the 'projects' link above to edit the list of projects.

test_app/app/views/projects/_form.html.haml
= form_for @project do |f|
  = f.label :name
  = f.text_field :name

  = f.submit

test_app/app/views/projects/_project.html.haml
%li
  %h2=link_to project.name, project
  %p
    =pluralize( project.entries.count, 'entry' )

test_app/app/views/projects/edit.html.haml
%h1
  Editing project
  %em=@project.name

%p
  =link_to 'Show project', @project

.tabs
  %ul
    %li
      %a{:href => '#entries'} Edit entries
    %li
      %a{:href => '#info'} Project information

  #entries
    #project-entries-container

  #info
    = render 'form'

test_app/app/views/projects/index.html.haml
%h1
  Projects

#projects-container
-#
  Backbone items get rendered herein.

test_app/app/views/projects/show.html.haml
%h1
  Project
  %em
    =@project.name

%p
  =link_to 'Edit project and entries', edit_project_path(@project)

%h2.entries
  Entries
%ol
  =render @project.entries

test_app/app/views/shared/_extra_head.html.erb
<link href='http://fonts.googleapis.com/css?family=Abel' rel='stylesheet' type='text/css'>

test_app/app/views/shared/_footer.html.haml
%footer.main
  %p
    This is a very simple app to demonstrate the very simple JS library
    =link_to 'Prolepsis.', 'https://github.com/mjhoy/prolepsis'

test_app/app/views/shared/_header.html.haml
%header.main
  %h1
    prolepsis / rails test app

test_app/app/views/shared/_navigation.html.haml
%nav.main
  %ul
    %li
      = link_to 'Home', root_path, :class => is_active?('home')
    %li
      = link_to 'Projects', projects_path, :class => is_active?('projects')

test_app/app/views/shared/_notice.html.haml
-if flash[:notice].present?
  %p.notice
    =flash[:notice]
-if flash[:alert].present?
  %p.alert
    =flash[:alert]

test_app/app/views/shared/backbone/_templates.html.erb
<!-- Project collection template -->
<script type="text/template" id="project-collection-template" >
  <a class="new" href="/projects/new">New project</a>

  <div class="new-form-container">
  </div>

  <ul class="projects models sortable" data-sort-url="<%= projects_sort_path %>">
  </ul>
</script>

<!-- Project template -->
<script type="text/template" id="project-template">
  <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
  <span class="name"><%%= name %></span>
  <span class="links">
    <a class="show" href="/projects/<%%= param %>">Show</a>
    <a class="edit" href="/projects/<%%= param %>/edit">Edit</a>
    <a class="delete" href="/projects/<%%= param %>" data-confirm="Are you sure?" data-method="delete">Delete</a>
    <a class="cancel" href="#">Cancel</a>
  </span>
  <div class="edit-form-container">

  </div>
</script>

<% if @project.present? -%>

  <!-- Project entries collection template -->
  <script type="text/template" id="project-entries-collection-template" >
    <a class="new" href="/projects/<%= @project.to_param %>/entries/new">New entry</a>

    <div class="new-form-container">
    </div>

    <ul class="entries models sortable" data-sort-url="<%= project_entries_sort_path(@project) %>">
    </ul>
  </script>

  <!-- Entry template -->
  <script type="text/template" id="entry-template">
    <span class="ui-icon ui-icon-arrowthick-2-n-s"></span>
    <span class="title"><%%= title %></span>
    <span class="links">
      <a class="edit" href="/projects/<%= @project.to_param %>/entries/<%%= param %>/edit">Edit</a>
      <a class="delete" href="/projects/<%= @project.to_param %>/entries/<%%= param %>" data-confirm="Are you sure?" data-method="delete">Delete</a>
      <a class="cancel" href="#">Cancel</a>
    </span>
    <div class="edit-form-container">
    </div>
  </script>

<% end -%>